# MLflow Configuration
MLFLOW_TRACKING_URI: "http://localhost:5000"
MLFLOW_BACKEND_STORE: "mlruns"
MLFLOW_SERVER_PORT: 5000
MLFLOW_SERVER_HOST: "localhost"
MLFLOW_DOCKER_IMAGE: "ghcr.io/mlflow/mlflow"
MLFLOW_DOCKER_CONTAINER_NAME: "mlflow_container"

# RabbitMQ Configuration
RABBITMQ_HOST: "localhost"
RABBITMQ_PORT: 5672
RABBITMQ_DASHBOARD_PORT: 15672
RABBITMQ_USER: "guest"
RABBITMQ_PASSWORD: "guest"
RABBITMQ_VHOST: "/"
RABBITMQ_SERVER_PATH: "/usr/sbin/rabbitmq-server"
RABBITMQ_DOCKER_IMAGE: "rabbitmq:3-management"
RABBITMQ_DOCKER_CONTAINER_NAME: "rabbitmq_container"

# Celery Configuration
CELERY_BROKER_URL: "amqp://guest:guest@localhost:5672/"
CELERY_RESULT_BACKEND: "redis://localhost:6379/0"

# Django Configuration
DJANGO_SECRET_KEY: "your-secret-key-here"
DEBUG: False
ALLOWED_HOSTS: []

# SRS (Simple RTMP Server) Configuration
SRS_SERVER_HOST: "localhost"
SRS_SERVER_PORT: 1935
SRS_HTTP_SERVER_PORT: 8080
SRS_DOCKER_IMAGE: "ossrs/srs:5"
SRS_DOCKER_CONTAINER_NAME: "srs_container"
